
CREATE DATABASE db_lista_kevin;
CREATE TABLE USUARIO(
    NICKNAME USUARIO
    NOMBRE_APELLIDO VARCHAR(20),
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    PRIMARY KEY(NICKNAME)
 );

 CREATE TABLE GENERO(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
 );

 
-- INSERTAR USUARIO

INSERT INTO USUARIO VALUES("Manuel","Manuel Arzamendia","manu@gmail.com","12345");
SELECT * FROM USUARIO;